<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        function Promise(fn) {
            var state = 'pending';
            var value;
            var deferred = null;
            function resolve(newValue) {
                try {
                    if (newValue && typeof newValue.then === 'function') {
                        newValue.then(resolve, reject);
                        return;
                    }
                    state = 'resolved';
                    value = newValue;
                    if (deferred) {
                        handle(deferred);
                    }
                } catch (e) {
                    reject(e);
                }
            }
            function reject(reason) {
                state = 'rejected';
                value = reason;
                if (deferred) {
                    handle(deferred);
                }
            }
            function handle(handler) {
                if (state === 'pending') {
                    deferred = handler;
                    return;
                }
                var handlerCallback;
                if (state === 'resolved') {
                    handlerCallback = handler.onResolved;
                } else {
                    handlerCallback = handler.onRejected;
                }
                if (!handlerCallback) {
                    if (state === 'resolved') {
                        handler.resolve(value);
                    } else {
                        handler.reject(value);
                    }
                    return;
                }
                var ret;
                try {
                    ret = handlerCallback(value);
                    handler.resolve(ret);
                } catch (e) {
                    handler.reject(e);
                }
            }
            this.then = function (onResolved, onRejected) {
                return new Promise(function (resolve, reject) {
                    handle({
                        onResolved: onResolved,
                        onRejected: onRejected,
                        resolve: resolve,
                        reject: reject
                    });
                });
            };
            fn(resolve, reject);
        }
        function getSomeJson() {
            return new Promise(function (resolve, reject) {
                var badJson = "<div>uh oh, this is not JSON at all!</div>";
                resolve(badJson);
            });
        }
        console.log("this first attempt will output nothing");
        getSomeJson().then(function (json) {
            var obj = JSON.parse(json);
            console.log(obj);
        }, function (error) {
            // Why is this? Since the unhandled exception took place in our callback to then(), it is being caught inside of handle(). This causes handle() to reject the promise that then() returned, not the promise we are already responding to, as that promise has already properly resolved.
            console.log('uh oh', error);
        });
        console.log("<br/>this second attempt handles the error correctly");

        // If you want to capture the above error, you need an error callback further downstream
        getSomeJson().then(function (json) {
            var obj = JSON.parse(json);
            console.log(obj);
        }).then(null, function (error) {
            console.log('uh oh', error);
        });
    </script>
</body>

</html>